### ISSUE TITLE
httpsに対応したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/rko-router#23]
2017年ともなるといよいよSSL必須ぽい流れなので、やっていきたい。
具体的なきっかけは、 asakusarb/oedo06#09

## やりたいこと
* [x] regional.rubykaigi.org のssl対応(すくなくともoedo06以降; 古いやつはまあいいか)
* [x] rubykaigi.orgのssl対応(すくなくとも2017以降; 古いやつはまあいいか)
* [x] cfp.rubykaigi.orgのssl対応

## 課題

* rko-routerで使っているbuildpackの https://github.com/ryandotsmith/nginx-buildpack がhttps_moduleを組み込んでない
  * PRはあるがマージ/リリースされてない(ryandotsmith/nginx-buildpack#57)
* rk.orgとregional.rk.orgの証明書が必要

## やったこと

* ryandotsmith/nginx-buildpack#57 を[cherry-pickしたfork](https://github.com/kakutani/nginx-buildpack)を試した(動いたっぽい)
* let's encryptで証明書をつくった(SANsっていうの? regional.rubykaigi.orgとrubykaigi.org用の証明書)
  * (ごにょごにょして作った証明書はkakutaniの手元にある状況)
* cfp.rubykaigi.orgの証明書はまだつくってない

## 次にやること

* [x] buildpackで使うnginxを https://github.com/kakutani/nginx-buildpack にする
* [x] proxy_passでhttpsを使うようにする(oedo06, kansai2017)
* nginxでregional.rubykaigi.org の証明書を使うようにする
* nginxでrubykaigi.org の証明書を使うようにする
* nginxでcfp.rubykaigi.org の証明書を使うようにする

## 困ってること: 証明書はどこにどうやって置けばいいんだろ

buildpackで動かしているnginxに証明書を読み込ませるにあたって、証明書をどこに置いたらいいのか…。

herokuのssl endpoint(いまのこう呼ぶのかな? heroluappの設定画面のSSLの項目)から証明書を追加しようとしたらうまくいかなかった(1回しか試してないので、なにかやり方がまずかったのかも?)。
推測しているのは、これはherokuのアプリ用のものであって、buildpackで動かしているnginxの証明書のことなんか知らんがな、っていうことなのでは…ということです。

自力で証明書を読み込ませるばあい、herokuのアプリ用のディスク的な領域のどこにどーやって証明書ファイルを送りこむのが手間がなくていいかな…というところで力尽きております 😲 
(publicになっているgithub上のリポジトリにpemファイルをセットで突っ込むのはべんりだけど行儀悪いよね…)

**Comment by kakutani** [comment]
oedo06 は regional.rubykaigi.org/oedo06 でアクセスできるようになった(リダイレクトされない)気がするのだけれど、同じ設定だと思われる kansai2017 がうまくいかない気がするけど、何か見落しているのかも…。

**Comment by sorah** [comment]
Heroku のアプリって Heroku router で HTTP も HTTPS も終端してるので、アプリ側は証明書もたなくていいんですよね。nginx には X-Forwarded-Proto: https つきで http トラフィックがくるようになるとおもいますよ <sup>[要出典]</sup>

**Comment by kakutani** [comment]
> Heroku のアプリって Heroku router で HTTP も HTTPS も終端してるので、アプリ側は証明書もたなくていいんですよね。nginx には X-Forwarded-Proto: https つきで http トラフィックがくるようになるとおもいます

なるほどっ。落ち着いて`certs:add`を試してみます。

**Comment by shyouhei** [comment]
現状:cfp.rubykaigi.orgはcloudflare側はSSL化されている。

**Comment by sorah** [comment]
`certs:add` すれば何も考えずにうごくんじゃないのって思ってるけどどうなんですかね。誰かやってみてほしい。

**Comment by sorah** [comment]
今なら certs:auto:enable か (Paid dymoのみ) https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by zunda** [comment]
`rko-router`アプリが`heroku domains:add regional.rubykaigi.org`されてるはずですよね？`regional.rubykaigi.org`を`CNAME`で`regional.rubykaigi.org.mastodon.zunda.ninja.herokudns.com`に向けてから`certs:auto:enable`すれば、`heroku certs:auto:enable`でしばらく待てば行けるはずです！

**Comment by snoozer05** [comment]
TODO: certs:auto:enable を試してみる

**Comment by takahashim** [comment]
`heroku certs:auto:enable -a rko-router` を試した所、`Apps using ACM are not allowed to have wildcard domains` でNGでした。むむーん。

**Comment by zunda** [comment]
あー。routerだし。その場合は、Let's Encryptのcertbotでwildcardの証明書を作ってもらって、

```
heroku certs:add fullchain.pem privkey.pem -a rko-router
```

するととりあえずhttpsで受けられるようになると思います。

この体制で続けるとすると、証明書の有効期限が3ヶ月くらいしかないので、(1) certbotを起動、(2) DNSチャレンジの`TXT`フィールドをDNSプロバイダに設定、(3) できた証明書を`heroku certs:update fullchain.pem privkey.pem`、という作業を2-3ヶ月ごとに繰り返さなきゃいけなくなるのが残念。

**Comment by zunda** [comment]
それだ!! 最近受けたリクエストのFQDNはアプリログ(`heroku logs`等)のHeroku routerからのログ(`heroku[router]`等)の`host=`欄を見ればわかります。

**Comment by sorah** [comment]
そんな事しなくても自明ではないか。 https://github.com/ruby-no-kai/rko-router/blob/master/config/nginx.conf.erb

**Comment by takahashim** [comment]
はい、そんな感じですが微妙なドメインもあるので捨てていい奴はこの際捨てたほうが良いかも…という気持ちもあります。

**Comment by springaki** [comment]
@sorah 先日お話した際に権限つけました

**Comment by sorah** [comment]
- #43 ふるい nginx-buildpack の雑草とり
- #44 nginx の設定をリファクタ等々、production 以外でもテストできるようにいい感じに
- #45 `/2019` から force https を開始

残タスクは可能な限り HTTPS を強制するところを増やす感じだ。あとは regional.rk.o とかがまだだな。

**Comment by springaki** [comment]
@sorah これ順次対応していけるんでしたっけ？
↑ のように `/2019` とか対応してみて何か問題ありました？

**Comment by kakutani** [comment]
これを起票したときの問題点は解決済み。
regional.rubykaigi.org も、まあ大丈夫そう。
force sslができていないけど、それは #89 で。
