### ISSUE TITLE
RubyKaigi2018 をトップページにする

### ISSUE THREAD

**Issue by nano041214** [ruby-no-kai/rko-router#32]
## やること

- [ ] https://github.com/ruby-no-kai/rko-router/pull/29/files と似たようなこと（spec 更新）
- [ ] https://github.com/ruby-no-kai/rko-router/pull/21/files と似たようなこと（redirect 先設定）

cf.) https://github.com/ruby-no-kai/rko-router/pull/31
で location 自体は追加済み

## いつやるか

https://github.com/ruby-no-kai/rubykaigi2018/pull/15

をマージしたら

**Comment by takahashim** [comment]
@nano041214 これって終わってます？

**Comment by amatsuda** [comment]
終わってた
