### ISSUE TITLE
Heroku やめる

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rko-router#81]

**Comment by sorah** [comment]
あとは切り替えるだけになった

**Comment by sorah** [comment]
まず

- www
- yami
- sapporo
- sponsorship (not sponsorships)
- j

をきりかえた

**Comment by sorah** [comment]
- 2006
- 2007
- 2008
- regional

もやった

**Comment by sorah** [comment]
- @

もやった。 https://rubykaigi.org までやったのでこれで作業は完了。あとは様子見て Heroku 撤収するだけ

**Comment by sorah** [comment]
本番に向けたテストがめちゃくちゃ落ちているがこれはこれまで force_https.conf が xfp の存在を前提にしてて、その前提のテストになっていて、そしてそもそも現状バグっていたのが直った、と見えるな

**Comment by sorah** [comment]
Heroku がいい感じにしてくれていた部分もありそうだったので全般的に叩いて直した https://github.com/ruby-no-kai/rko-router/pull/85

**Comment by sorah** [comment]
対本番でも通った

```
Finished in 27 seconds (files took 0.39464 seconds to load)
130 examples, 0 failures, 2 pending
```

**Comment by sorah** [comment]
GitHub Pages がたぶん北米にある都合ファーストタッチレイテンシがつらいので us-west-2 に移すか。

**Comment by sorah** [comment]
他リポジトリとのかかわりも書いた詳細は esa に残した https://rubykaigi.esa.io/posts/1241

**Comment by kakutani** [comment]
done?
